services:
  server:
    build: ./Part 5
    container_name: server
  proxy:
    build: ./Part 6
    container_name: proxy
    ports:
      - 80:8080
    volumes:
      - ./Part 6/nginx.conf:/etc/nginx/nginx.conf